### PR TITLE
unbreak InvariantTicksPerSecond() for OpenBSD/powerpc64

### PR DESCRIPTION
**Pull request by jasperla**

### CODE REVIEW

**Comment by jan-wassenberg** [comment]
Hi @jasperla, thanks for opening the PR, are you able to sign the [CLA](https://cla.developers.google.com/)?

Alternatively, would you be willing to give an English-language description so I could re-implement this without needing a CLA?

**Comment by jasperla** [comment]
@googlebot I signed it!

**Comment by jasperla** [comment]
> Hi @jasperla, thanks for opening the PR, are you able to sign the [CLA](https://cla.developers.google.com/)?
> 
> Alternatively, would you be willing to give an English-language description so I could re-implement this without needing a CLA?

Seems I missed your comment earlier -- the CLA should be good now.

**Comment by jan-wassenberg** [comment]
@jasperla indeed, thanks for doing the CLA and fixing this :)

**Pull request merged**
