### PR TITLE
Add missing include

### PR DESCRIPTION
**Pull request by vks**
This should make the `vector_test` compile again.

### CODE REVIEW

**Comment by jan-wassenberg** [comment]
Thanks for mentioning! We need to sort includes alphabetically; I'll take care of this in the next push.

**Comment by CDLuminate** [comment]
This fixes build for `vector_test.cc`.

**Comment by jan-wassenberg** [comment]
I'm sorry about the delay here, this patch is included in a larger change that adds (theoretical) support for arm/ppc and greatly accelerates HighwayHashCatT. I hope to push it tomorrow or perhaps Fri.

**Comment by vks** [comment]
This has been fixed on master. Thanks!

**Comment by jan-wassenberg** [comment]
Thanks for updating the issue :)

**Pull request closed without merging**
